name: Gradle Publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Set env variables
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Publish to Repository
        uses: gradle/gradle-build-action@v2
        with:
          arguments: 'publish --stacktrace'
        env:
          CI_VERSION: ${{ steps.vars.outputs.tag }}
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
